name: qt actions

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Download Qt Online Installer
      run: curl -L "https://download.qt.io/official_releases/online_installers/qt-online-installer-mac-x64-online.dmg" -o qt-installer.dmg

    - name: Mount DMG and Copy Installer
      run: |
        hdiutil attach qt-installer.dmg
        cp -R "/Volumes/qt-online-installer-macOS-x64-4.9.0/qt-online-installer-macOS-x64-4.9.0.app" qt-installer.app
        hdiutil detach "/Volumes/qt-online-installer-macOS-x64-4.9.0"
    - name: Installing Qt
      env:
        QT_INSTALLER_JWT_TOKEN: ${{ secrets.QT_INSTALLER_JWT_TOKEN }}
      run: |
        ./qt-installer.app/Contents/MacOS/qt-online-installer-macOS-x64-4.9.0 \
          --root ${{github.workspace}}/qt \
          --accept-licenses --accept-messages --confirm-command --accept-obligations \
          install qt.qt6.673.clang_64 qt.qt6.673.addons.qtmultimedia
          
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="${{github.workspace}}/qt/lib/cmake"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
